language: node_js
node_js:
  - "stable"
  - "4"
  - "0.12"
  - "0.10"

# Install grunt-cli globally before installing all dependencies, including grunt
before_install:
  - npm install grunt-cli -g
